# =============================================================================
# Example CloudNativePG Cluster with pg_stream extension.
#
# Prerequisites:
#   1. A Kubernetes cluster with the CNPG operator installed
#   2. The pg_stream Docker image available in the cluster
#      (either from GHCR or loaded locally with `kind load docker-image`)
#
# Deploy:
#   kubectl apply -f cnpg/cluster-example.yaml
#
# Connect:
#   kubectl exec -it pg-stream-demo-1 -- psql -U postgres -d app
# =============================================================================
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-stream-demo
  labels:
    app.kubernetes.io/name: pg-stream
    app.kubernetes.io/component: database
spec:
  # Number of PostgreSQL instances (1 primary + N-1 replicas)
  instances: 3

  # Docker image with pg_stream pre-installed.
  # Replace <owner> and <version> with your GHCR coordinates.
  imageName: ghcr.io/<owner>/pg_stream:<version>

  postgresql:
    # Required: load the extension shared library at server start
    shared_preload_libraries:
      - pg_stream

    parameters:
      # Not required for trigger-based CDC, but needed if migrating
      # to logical-replication CDC in the future.
      # wal_level: logical

      # Recommended if using logical replication CDC (not needed for triggers)
      # max_replication_slots: "10"

      # Recommended: scheduler bgworker + refresh workers
      max_worker_processes: "8"

      # Optional: tune scheduler interval (default: 1000ms)
      # pg_stream.scheduler_interval_ms: "1000"

      # Optional: tune minimum schedule duration (default: 60s)
      # pg_stream.min_schedule_seconds: "60"

  bootstrap:
    initdb:
      database: app
      owner: app
      # Automatically create the extension on database initialization
      postInitSQL:
        - CREATE EXTENSION pg_stream

  storage:
    size: 10Gi
    # Replace with your cluster's storage class
    storageClass: standard

  # Optional: resource limits
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 500m
  #   limits:
  #     memory: 2Gi
  #     cpu: 2000m

  # Optional: backup configuration (recommended for production)
  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://your-bucket/cnpg-backups
  #     s3Credentials:
  #       accessKeyId:
  #         name: cnpg-s3-creds
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: cnpg-s3-creds
  #         key: ACCESS_SECRET_KEY
