-- pg_trickle 0.14.0 -> 0.15.0 upgrade script
--
-- v0.15.0: External Test Suites & Integration
--
-- VOL-1: volatile_function_policy GUC
--   Registered via pgrx GUC infrastructure (no DDL needed — GUC is
--   automatically available after extension upgrade).
--
-- TRUNC-1: TRUNCATE capture for trigger-mode CDC
--   Already implemented in v0.14.0 via CDC TRUNCATE triggers. No schema
--   changes needed for this release.
--
-- No catalog schema changes in this upgrade step.
